name: Run Decal AI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - run: pip install -r requirements.txt
      - run: mkdir -p data/raw
      - run: python main.py

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  deploy:
    needs: run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v3
